name: Test Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  list-files:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: List files in the repository
      run: ls -la