name: Déployer Le Serveur Rust

on:
  workflow_run:
    workflows: ["Créer le fichier .env"]
    types:
      - completed

jobs:
  deploy-rust-server:
    runs-on: self-hosted
    needs: create-env-file
    
    steps:
    - name: Checkout du code
      uses: actions/checkout@v2
      
    - name: Démarrer le serveur Rust
      run: |
        docker compose -f compose.yml up -d