name: Déployer Le Serveur Rust

on:
  workflow_dispatch:

jobs:
  deploy-rust-server:
    runs-on: self-hosted
    
    steps:
    - name: Checkout du code
      uses: actions/checkout@v2
      
    - name: Démarrer le serveur Rust
      run: |
        docker compose -f compose.yml up -d