name: Télécharger les plugins Oxide

on:
  push:
    branches:
      - main

jobs:
  download_plugins:
    runs-on: self-hosted
    
    steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Configurer Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.3'

    - name: Installer les dépendances
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Télécharger les plugins
      run: |
        import requests
        import os

        plugin_file = os.path.expanduser('~/rust/local-files/plugin.list')
        plugins_dir = os.path.expanduser('~/rust/files/oxide/plugins')
        
        with open(plugin_file, 'r') as file:
            plugins = file.read().splitlines()

        os.makedirs(plugins_dir, exist_ok=True)

        for plugin in plugins:
            url = f"https://umod.org/plugins/{plugin}.cs"
            response = requests.get(url)
            if response.status_code == 200:
                plugin_path = os.path.join(plugins_dir, f"{plugin}.cs")
                with open(plugin_path, 'wb') as f:
                    f.write(response.content)
                print(f"Téléchargé : {plugin}.cs")
            else:
                print(f"Erreur lors du téléchargement de {plugin}.cs : {response.status_code}")
      shell: python
      
    - name: Archiver les plugins téléchargés
      uses: actions/upload-artifact@v2
      with:
        name: downloaded-plugins
        path: downloaded_plugins